# helm/tiksimpro/Chart.yaml
apiVersion: v2
name: tiksimpro
description: TikSimPro - Automated TikTok Content Generator
type: application
version: 1.0.0
appVersion: "1.0.0"

# Dependencies:
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
